import { PERMISSIONS, type PermissionCode } from "./catalog.js";

/**
 * Roles preset sembrados en cada tenant nuevo (editables por el dueño).
 * Referencia: docs/analisis/04-modelo-datos/4.6-usuarios-sucursales.md
 *
 * Subset Hito 1 retail/abarrotes. Los presets de salud (medico/enfermera/
 * recepcion) se siembran cuando el tenant activa esa vertical (Hito 3).
 *
 * El permiso `*` (wildcard) significa "todos los permisos actuales y futuros":
 * útil para el rol `dueno` para que adquiera permisos nuevos sin migration.
 */
export interface PresetRole {
  codigo: string;
  nombre: string;
  descripcion: string;
  permisos: PermissionCode[] | ["*"];
}

const P = PERMISSIONS;

export const PRESET_ROLES_RETAIL: ReadonlyArray<PresetRole> = Object.freeze([
  {
    codigo: "dueno",
    nombre: "Dueño",
    descripcion: "Acceso total al tenant (no incluye billing SaaS, eso es del Superadmin)",
    permisos: ["*"],
  },
  {
    codigo: "gerente",
    nombre: "Gerente",
    descripcion: "Operación completa de la sucursal: cajas, ventas, inventario, reportes",
    permisos: [
      P.POS_USAR,
      P.VENTAS_LEER,
      P.VENTAS_CREAR,
      P.VENTAS_CANCELAR,
      P.VENTAS_DEVOLVER,
      P.VENTAS_COTIZAR,
      P.VENTAS_APLICAR_DESCUENTO,
      P.VENTAS_APLICAR_DESCUENTO_ALTO,
      P.APARTADOS_LEER,
      P.APARTADOS_CREAR,
      P.APARTADOS_ABONAR,
      P.APARTADOS_LIQUIDAR,
      P.APARTADOS_CANCELAR,
      P.CXC_LEER,
      P.CXC_CREAR,
      P.CXC_COBRAR,
      P.CXC_CONDONAR,
      P.COTIZACIONES_LEER,
      P.COTIZACIONES_ENVIAR,
      P.COTIZACIONES_GESTIONAR_ESTADO,
      P.PEDIDOS_LEER,
      P.PEDIDOS_CREAR,
      P.PEDIDOS_APROBAR,
      P.PEDIDOS_GESTIONAR,
      P.PEDIDOS_CONVERTIR_VENTA,
      P.RECARGAS_LEER,
      P.RECARGAS_VENDER,
      P.RECARGAS_REEMBOLSAR,
      P.RECARGAS_CONFIGURAR,
      P.PRODUCTOS_LEER,
      P.PRODUCTOS_CREAR,
      P.PRODUCTOS_ACTUALIZAR,
      P.PRODUCTOS_ARCHIVAR,
      P.PRODUCTOS_BULK_IMPORT,
      P.INVENTARIO_LEER,
      P.INVENTARIO_AJUSTAR,
      P.INVENTARIO_TRANSFERIR,
      P.PRECIOS_LEER,
      P.PRECIOS_MODIFICAR,
      P.PRECIOS_REGLA_CREAR,
      P.CLIENTES_LEER,
      P.CLIENTES_CREAR,
      P.CLIENTES_ACTUALIZAR,
      P.CLIENTES_FIADO_GESTIONAR,
      P.CAJA_ABRIR,
      P.CAJA_CERRAR,
      P.CAJA_CERRAR_FORZOSO,
      P.CAJA_MOVIMIENTO_CREAR,
      P.CORTE_CONSULTAR,
      P.CORTE_IMPRIMIR,
      P.CFDI_LEER,
      P.CFDI_EMITIR,
      P.CFDI_CANCELAR,
      P.REPORTES_VENTAS,
      P.REPORTES_INVENTARIO,
      P.REPORTES_FINANCIEROS,
      P.USUARIOS_LEER,
      P.USUARIOS_CREAR,
      P.USUARIOS_ACTUALIZAR,
      P.USUARIOS_ARCHIVAR,
      P.USUARIOS_ASIGNAR_ROL,
      P.USUARIOS_RESET_PASSWORD,
      P.ROLES_LEER,
      P.SUCURSALES_LEER,
      P.SUCURSALES_ACTUALIZAR,
      P.CAJAS_LEER,
      P.CAJAS_CREAR,
      P.CAJAS_ACTUALIZAR,
      P.CAJAS_ARCHIVAR,
      P.CONFIGURACION_LEER,
      P.PACIENTES_LEER,
      P.PACIENTES_CREAR,
      P.PACIENTES_ACTUALIZAR,
      P.PACIENTES_ARCHIVAR,
      P.MEDICOS_LEER,
      P.AGENDA_LEER,
      P.AGENDA_GESTIONAR,
      P.AGENDA_BLOQUEAR,
      P.CITAS_LEER,
      P.CITAS_CREAR,
      P.CITAS_GESTIONAR,
      P.CITAS_CHECKIN,
      P.CITAS_CANCELAR,
      P.CONSULTAS_LEER,
      P.RECETAS_LEER,
      P.MASCOTAS_LEER,
      P.MASCOTAS_CREAR,
      P.MASCOTAS_ACTUALIZAR,
      P.MASCOTAS_ARCHIVAR,
      P.VACUNAS_LEER,
      P.VACUNAS_APLICAR,
      P.VACUNAS_GESTIONAR_CARTILLA,
      P.CAMAS_LEER,
      P.CAMAS_GESTIONAR,
      P.HOSPITALIZACION_LEER,
      P.HOSPITALIZACION_CREAR,
      P.HOSPITALIZACION_ALTA,
      P.MEDICACION_PROGRAMAR,
      P.KARDEX_LEER,
      P.KARDEX_APLICAR,
      P.KARDEX_REPROGRAMAR,
      P.CFDIS_RECIBIDOS_LEER,
      P.CFDIS_RECIBIDOS_UPLOAD,
      P.CFDIS_RECIBIDOS_CATEGORIZAR,
      P.CFDIS_RECIBIDOS_CANCELAR,
      P.COMPRAS_OC_LEER,
      P.COMPRAS_OC_CREAR,
      P.COMPRAS_OC_AUTORIZAR,
      P.COMPRAS_OC_RECIBIR,
      P.DIOT_GENERAR,
      P.ECOMMERCE_CONFIGURAR,
      P.ECOMMERCE_PUBLICAR_PRODUCTO,
      P.ECOMMERCE_PEDIDOS_LEER,
      P.ECOMMERCE_PEDIDOS_GESTIONAR,
      P.ECOMMERCE_RESENAS_MODERAR,
      P.ECOMMERCE_ENVIOS_GESTIONAR,
      P.PROMOCIONES_GESTIONAR,
      P.SEGMENTOS_GESTIONAR,
      P.CAMPANAS_GESTIONAR,
      P.CAMPANAS_ENVIAR,
      P.PLANTILLAS_GESTIONAR,
      P.LEALTAD_GESTIONAR,
      P.SYNC_USAR,
    ],
  },
  {
    codigo: "cajero",
    nombre: "Cajero",
    descripcion: "Operar POS, cobrar, devolver y manejar su caja",
    permisos: [
      P.POS_USAR,
      P.VENTAS_LEER,
      P.VENTAS_CREAR,
      P.VENTAS_DEVOLVER,
      P.VENTAS_APLICAR_DESCUENTO,
      P.APARTADOS_LEER,
      P.APARTADOS_CREAR,
      P.APARTADOS_ABONAR,
      P.APARTADOS_LIQUIDAR,
      P.CXC_LEER,
      P.CXC_COBRAR,
      P.COTIZACIONES_LEER,
      P.PEDIDOS_LEER,
      P.PEDIDOS_CONVERTIR_VENTA,
      P.RECARGAS_LEER,
      P.RECARGAS_VENDER,
      P.PRODUCTOS_LEER,
      P.INVENTARIO_LEER,
      P.PRECIOS_LEER,
      P.CLIENTES_LEER,
      P.SUCURSALES_LEER,
      P.CAJAS_LEER,
      P.CAJA_ABRIR,
      P.CAJA_CERRAR,
      P.CAJA_MOVIMIENTO_CREAR,
      P.CORTE_CONSULTAR,
      P.CORTE_IMPRIMIR,
      P.CFDI_EMITIR,
      P.SYNC_USAR,
    ],
  },
  {
    codigo: "vendedor",
    nombre: "Vendedor",
    descripcion: "Cajero + cotizaciones + alta de clientes + comisiones propias",
    permisos: [
      P.POS_USAR,
      P.VENTAS_LEER,
      P.VENTAS_CREAR,
      P.VENTAS_DEVOLVER,
      P.VENTAS_COTIZAR,
      P.VENTAS_APLICAR_DESCUENTO,
      P.APARTADOS_LEER,
      P.APARTADOS_CREAR,
      P.APARTADOS_ABONAR,
      P.APARTADOS_LIQUIDAR,
      P.CXC_LEER,
      P.CXC_CREAR,
      P.CXC_COBRAR,
      P.COTIZACIONES_LEER,
      P.COTIZACIONES_ENVIAR,
      P.COTIZACIONES_GESTIONAR_ESTADO,
      P.PEDIDOS_LEER,
      P.PEDIDOS_CREAR,
      P.PEDIDOS_GESTIONAR,
      P.PEDIDOS_CONVERTIR_VENTA,
      P.RECARGAS_LEER,
      P.RECARGAS_VENDER,
      P.PRODUCTOS_LEER,
      P.INVENTARIO_LEER,
      P.PRECIOS_LEER,
      P.CLIENTES_LEER,
      P.CLIENTES_CREAR,
      P.CLIENTES_ACTUALIZAR,
      P.SUCURSALES_LEER,
      P.CAJAS_LEER,
      P.CAJA_ABRIR,
      P.CAJA_CERRAR,
      P.CAJA_MOVIMIENTO_CREAR,
      P.CORTE_CONSULTAR,
      P.CORTE_IMPRIMIR,
      P.CFDI_EMITIR,
      P.ECOMMERCE_PEDIDOS_LEER,
      P.ECOMMERCE_PEDIDOS_GESTIONAR,
      P.PROMOCIONES_GESTIONAR,
      P.CAMPANAS_GESTIONAR,
      P.LEALTAD_GESTIONAR,
      P.SYNC_USAR,
    ],
  },
  {
    codigo: "almacen",
    nombre: "Almacén",
    descripcion: "Inventario, recepciones y transferencias entre sucursales",
    permisos: [
      P.PRODUCTOS_LEER,
      P.PRODUCTOS_CREAR,
      P.PRODUCTOS_ACTUALIZAR,
      P.PRODUCTOS_BULK_IMPORT,
      P.INVENTARIO_LEER,
      P.INVENTARIO_AJUSTAR,
      P.INVENTARIO_TRANSFERIR,
      P.PRECIOS_LEER,
      P.PEDIDOS_LEER,
      P.PEDIDOS_GESTIONAR,
      P.REPORTES_INVENTARIO,
      P.ECOMMERCE_PEDIDOS_LEER,
      P.ECOMMERCE_PEDIDOS_GESTIONAR,
      P.ECOMMERCE_ENVIOS_GESTIONAR,
      P.COMPRAS_OC_LEER,
      P.COMPRAS_OC_CREAR,
      P.COMPRAS_OC_RECIBIR,
    ],
  },
  {
    codigo: "contador_interno",
    nombre: "Contador interno",
    descripcion:
      "Reportes financieros, emisión CFDI, despacho (CFDIs recibidos + DIOT); sin acceso a POS",
    permisos: [
      P.VENTAS_LEER,
      P.PRODUCTOS_LEER,
      P.CLIENTES_LEER,
      P.CFDI_LEER,
      P.CFDI_EMITIR,
      P.CFDI_CANCELAR,
      P.CXC_LEER,
      P.CXC_COBRAR,
      P.REPORTES_VENTAS,
      P.REPORTES_INVENTARIO,
      P.REPORTES_FINANCIEROS,
      P.CFDIS_RECIBIDOS_LEER,
      P.CFDIS_RECIBIDOS_UPLOAD,
      P.CFDIS_RECIBIDOS_CATEGORIZAR,
      P.CFDIS_RECIBIDOS_CANCELAR,
      P.COMPRAS_OC_LEER,
      P.COMPRAS_OC_AUTORIZAR,
      P.DIOT_GENERAR,
    ],
  },
  {
    codigo: "medico",
    nombre: "Médico",
    descripcion: "Consulta SOAP, recetas, expediente clínico (tenants vertical Salud)",
    permisos: [
      P.PACIENTES_LEER,
      P.PACIENTES_CREAR,
      P.PACIENTES_ACTUALIZAR,
      P.MEDICOS_LEER,
      P.MEDICOS_EDITAR_PERFIL,
      P.SUCURSALES_LEER,
      P.AGENDA_LEER,
      P.AGENDA_GESTIONAR,
      P.AGENDA_BLOQUEAR,
      P.CITAS_LEER,
      P.CITAS_GESTIONAR,
      P.CONSULTAS_LEER,
      P.CONSULTAS_CREAR,
      P.CONSULTAS_FIRMAR,
      P.CONSULTAS_ENMENDAR,
      P.RECETAS_LEER,
      P.RECETAS_EMITIR,
      P.RECETAS_CANCELAR,
      P.MASCOTAS_LEER,
      P.MASCOTAS_CREAR,
      P.MASCOTAS_ACTUALIZAR,
      P.VACUNAS_LEER,
      P.VACUNAS_APLICAR,
      P.CAMAS_LEER,
      P.HOSPITALIZACION_LEER,
      P.HOSPITALIZACION_CREAR,
      P.MEDICACION_PROGRAMAR,
      P.KARDEX_LEER,
      P.KARDEX_APLICAR,
      P.KARDEX_REPROGRAMAR,
      P.LABORATORIO_LEER,
      P.LABORATORIO_SOLICITAR,
      P.LABORATORIO_CARGAR_RESULTADO,
      P.LABORATORIO_CANCELAR,
      P.IMAGENOLOGIA_LEER,
      P.IMAGENOLOGIA_SOLICITAR,
      P.IMAGENOLOGIA_CARGAR_RESULTADO,
      P.IMAGENOLOGIA_CANCELAR,
      P.DOCTORALIA_PERFIL_GESTIONAR,
      P.DOCTORALIA_PERFIL_PUBLICAR,
      P.DOCTORALIA_RESENAS_LEER,
      P.DOCTORALIA_RESENAS_RESPONDER,
      P.DOCTORALIA_RESENAS_DENUNCIAR,
      P.PHR_PUBLICAR_REGISTRO,
      P.PHR_SOLICITAR_CONSENT,
      P.PHR_LEER_CONSENTIDO,
    ],
  },
  {
    codigo: "enfermera",
    nombre: "Enfermera/Asistente clínico",
    descripcion: "Asiste al médico: checkin, signos vitales, vacunas (tenants vertical Salud)",
    permisos: [
      P.PACIENTES_LEER,
      P.PACIENTES_CREAR,
      P.PACIENTES_ACTUALIZAR,
      P.MEDICOS_LEER,
      P.SUCURSALES_LEER,
      P.AGENDA_LEER,
      P.CITAS_LEER,
      P.CITAS_CHECKIN,
      P.CONSULTAS_LEER,
      P.RECETAS_LEER,
      P.MASCOTAS_LEER,
      P.MASCOTAS_CREAR,
      P.MASCOTAS_ACTUALIZAR,
      P.VACUNAS_LEER,
      P.VACUNAS_APLICAR,
      P.CAMAS_LEER,
      P.HOSPITALIZACION_LEER,
      P.KARDEX_LEER,
      P.KARDEX_APLICAR,
      P.LABORATORIO_LEER,
      P.LABORATORIO_CARGAR_RESULTADO,
      P.IMAGENOLOGIA_LEER,
      P.IMAGENOLOGIA_CARGAR_RESULTADO,
    ],
  },
  {
    codigo: "recepcion",
    nombre: "Recepción",
    descripcion: "Agenda + checkin + cobro al alta (tenants vertical Salud)",
    permisos: [
      P.PACIENTES_LEER,
      P.PACIENTES_CREAR,
      P.PACIENTES_ACTUALIZAR,
      P.MEDICOS_LEER,
      P.SUCURSALES_LEER,
      P.AGENDA_LEER,
      P.AGENDA_GESTIONAR,
      P.CITAS_LEER,
      P.CITAS_CREAR,
      P.CITAS_GESTIONAR,
      P.CITAS_CHECKIN,
      P.CITAS_CANCELAR,
      P.CONSULTAS_LEER,
      P.RECETAS_LEER,
      P.MASCOTAS_LEER,
      P.MASCOTAS_CREAR,
      P.MASCOTAS_ACTUALIZAR,
      P.VACUNAS_LEER,
      P.VACUNAS_APLICAR,
      P.VENTAS_LEER,
      P.VENTAS_CREAR,
      P.CLIENTES_LEER,
      P.CLIENTES_CREAR,
      P.CLIENTES_ACTUALIZAR,
      P.CAJA_ABRIR,
      P.CAJA_CERRAR,
      P.CAJA_MOVIMIENTO_CREAR,
      P.CFDI_EMITIR,
      P.CAMAS_LEER,
      P.CAMAS_GESTIONAR,
      P.HOSPITALIZACION_LEER,
      P.HOSPITALIZACION_ALTA,
      P.KARDEX_LEER,
      P.LABORATORIO_LEER,
      P.LABORATORIO_CARGAR_RESULTADO,
      P.IMAGENOLOGIA_LEER,
      P.IMAGENOLOGIA_CARGAR_RESULTADO,
    ],
  },
]);
